### ISSUE TITLE
Drop Bower dependencies of gh-pages branch (?)

### ISSUE THREAD

**Issue by zdroid** [watilde/chest#72]
I've just noticed there are Bootstrap and jQuery Bower dependencies on `gh-pages` branch. Are they really required? They look pretty redundant to me there. :wink:

**Comment by watilde** [comment]
Thanks for requesting this. It's still used and really useful to manage the dependencies version.
+ https://github.com/watilde/chest/blob/gh-pages/index.html#L8
+ https://github.com/watilde/chest/blob/gh-pages/index.html#L80
+ https://github.com/watilde/chest/blob/gh-pages/index.html#L81

So let me say they are required.

**Comment by zdroid** [comment]
Yep, but almost no code is used from those libraries. Site can run fine
without them.
